services:
  nats:
    image: nats:2.11
    ports: ["4222:4222"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nutsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=updates
      - DB_URL=jdbc:postgresql://db:5432/nutsdb
      - DB_USER=postgres
      - DB_PASS=1234
    depends_on:
      - nats
      - db

volumes:
  pgdata:
